#!/usr/bin/env bash
# Transfers a file from School's client to another.
# It takes four parameters
#!/usr/bin/env bash

# Check if all four arguments are provided
if [ $# -ne 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
