#!/usr/bin/env bash
# Install nginx
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start
echo 'Hello World' | sudo tee /var/www/html/index.html
printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
