#!/usr/bin/env bash
# Install nginx
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start

#update configuration file
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80;
	server_name localhost;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		root /var/www/html;
		index index.html index.htm;
	}
}
EOF'
sudo service nginx restart
