#!/usr/bin/env bash

# Install nginx
apt-get update
apt-get install -y nginx

# Configure nginx to listen on port 80
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 http://cuberule.com/;
    }
}" > /etc/nginx/sites-available/default

# Create the default index.html file
echo "Hello World" > /var/www/html/index.html

# Restart nginx
service nginx restart
