#!/usr/bin/env bash
# Install nginx
sudo apt -y update
sudo apt -y install nginx
sudo service nginx start

#update configuration file
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
	listen 80;
	server_name localhost;

	error_page 404 /404.html;

	location = /404.html {
		root /var/www/html;
		internal;
	}

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	location / {
		root /var/www/html;
		index index.html index.htm;
	}
}
EOF'
sudo bash -c "echo "Ceci n\'est pas une page" | sudo tee /var/www/html/404.html"
sudo service nginx restart
