#!/usr/bin/env bash
#Prints bad luck, good luck and Best School
NUM=0
while [ $NUM -lt 10 ]
do
	if [ $NUM -eq 3 ]; then
		echo "bad luck"
	elif [ $NUM -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((NUM=NUM+1))
done
