#!/usr/bin/env bash
#Printts 12 hours times 59 minutes
MINUTE=0
HOUR=0
while [ $HOUR -lt 14 ]
do
	while [ $MINUTE -lt 60 ]
	do
		if [ $MINUTE -eq 1 ]; then
			echo "Hour: $HOUR"
			((HOUR=HOUR+1))
		fi
		if [ $HOUR -ne 14 ]; then
			echo "$MINUTE"
		fi
		((MINUTE=MINUTE+1))
		if [ $MINUTE -eq 60 ]; then
			if [ $HOUR -eq 13 ]; then
				break
			else
				((MINUTE=1))
			fi
		fi
	done
	break
done
