#!/usr/bin/env bash
#This script changes my home IP address
cp /etc/hosts ~/hosts.new
sed -i 's/^127.*$ localhost/127.0.0.2	localhost/' ~/hosts.new
echo "facebook.com	8.8.8.8" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
