#!/bin/bash
# Update nginx configuration to run as nginx user
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/^listen .*/listen 8080;/' /etc/nginx/sites-available/default
service nginx restart
